name: Android

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Install Qt
      uses: johanremilien/install-qt-action@v2
      with:
        target: android

    - name: qmake
      run: qmake

    - name: make
      run: make

    - name: make check
      run: make check
