name: iOS-upload

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: macos-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up ruby env
        uses: ruby/setup-ruby@v1.138.0
        with:
          ruby-version: 3.2.1
          bundler-cache: true

      - name: install tree
        run: brew install tree

      - name: Install Qt
        uses: johanremilien/install-qt-action@v3
        with:
          target: ios
          modules: qtpurchasing

      - name: Apply Qt patch (Switch to using Xcode's new build system)
        run: |
          cd ${{ env.Qt5_DIR }}
          echo "wget patch (see https://codereview.qt-project.org/c/qt/qtbase/+/353118)"
          wget https://codereview.qt-project.org/changes/qt%2Fqtbase\~353118/revisions/2/patch\?zip\&path\=mkspecs%2Fmacx-xcode%2FWorkspaceSettings.xcsettings -O patch.zip
          echo "unzip patch"
          unzip patch.zip; rm patch.zip
          echo "apply patch"
          git apply a5273d4.diff; rm a5273d4.diff
          cd -

      - name: Use python3 as interpreter in devices.py
        run: sed -i '' 's/\usr\/bin\/python/\usr\/bin\/python3/g' ${{ env.Qt5_DIR }}/mkspecs/features/uikit/devices.py

      - name: qmake
        run: qmake

      - name: make (generate qrc_ and moc_ files)
        run: make -j$(sysctl -n hw.physicalcpu) -i

      - name: Dummy fix for WWDR
        run: |
          tmpfile=$(mktemp /tmp/wwdr-cert.cer)
          curl -f -o $tmpfile https://www.apple.com/certificateauthority/AppleWWDRCAG3.cer && security import $tmpfile /Users/runner/Library/Keychains/login.keychain-db

      - name: Decode signing certificate into a file
        env:
         CERTIFICATE_BASE64: ${{ secrets.IOS_DIST_SIGNING_KEY }}
        run: |
          echo $CERTIFICATE_BASE64 | base64 --decode > signing-cert.p12

      - name: Build iOS binary
        run: bundle exec fastlane ios deploy
        env:
          ASC_KEY_ID: ${{ secrets.ASC_KEY_ID }}
          ASC_ISSUER_ID: ${{ secrets.ASC_ISSUER_ID }}
          ASC_KEY: ${{ secrets.ASC_PRIVATE_KEY }}
          SIGNING_KEY_PASSWORD: ${{ secrets.IOS_DIST_SIGNING_KEY_PASSWORD }}
          SIGNING_KEY_FILE_PATH: signing-cert.p12

      - name: Upload IPA
        if: always()
        uses: actions/upload-artifact@v3
        with:
          name: IPA
          path: ${{ github.workspace }}/*.ipa

      - run: echo "APP_PATH=$(readlink -f ${{ github.workspace }}/Release-iphoneos/*.app)" >> $GITHUB_ENV
      - name: Upload APP
        if: always()
        uses: actions/upload-artifact@v3
        with:
          name: APP
          path: ${{ env.APP_PATH }}

      - name: Upload dSYM
        if: always()
        uses: actions/upload-artifact@v3
        with:
          name: dSYM
          path: ${{ github.workspace }}/Release-iphoneos/*.app.dSYM

      - name: tree
        if: always()
        run: tree .
