name: Ubuntu

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Upload strings to Localazy
      uses: localazy/upload@v1
      with:
        workdir: ${{ github.workspace }}/translations
        read_key: ${{ secrets.LOCALAZY_READ_KEY }}
        write_key: ${{ secrets.LOCALAZY_WRITE_KEY }}

    - name: Install Qt
      uses: johanremilien/install-qt-action@v3
      with:
        modules: qtpurchasing qtwebengine

    - name: qmake
      run: qmake

    - name: make
      run: make -j$(nproc)

    - name: make check
      run: make -j$(nproc) check

    - name: tree
      run: tree .
