name: Ubuntu

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Install Qt
      uses: johanremilien/install-qt-action@v2

    - name: qmake
      run: qmake

    - name: make
      run: make -j$(nproc)

    - name: make check
      run: make -j$(nproc) check

    - name: tree
      run: tree .
